apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
  labels:
    app: fe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - name: fe-app
        image:  gcr.io/alpha-1996/react:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fe-app
spec:
  type: LoadBalancer
  selector:
    app: fe-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
